### ISSUE TITLE
Writing more then 65kb results in corrupted data

### ISSUE THREAD

**Issue by ulfgebhardt** [oblador/react-native-keychain#184]
### Writing more then 65kb results in corrupted data

reading the corrupt data results in
`Unexpected token [...] in JSON at position 65536`

### Data written
![image](https://user-images.githubusercontent.com/1238238/51557987-a8e80000-1e7e-11e9-9e42-a7c905778bc2.png)

### Data read
![image](https://user-images.githubusercontent.com/1238238/51558016-b604ef00-1e7e-11e9-8837-47bafd1143ac.png)

### The Code
![image](https://user-images.githubusercontent.com/1238238/51558134-02e8c580-1e7f-11e9-9b1f-c89ffb175ef3.png)
Writing 30k Integers into the buffer

### More Context
![image](https://user-images.githubusercontent.com/1238238/51558078-d6cd4480-1e7e-11e9-8011-00813c87f02c.png)

### The Error
![image](https://user-images.githubusercontent.com/1238238/51558090-e2207000-1e7e-11e9-8620-62b594bfe10f.png)

### The current Solution
Split up the data into buckets, have another key which indexes the buckets

This reduces speed, since there is more read Operations.

![image](https://user-images.githubusercontent.com/1238238/51558681-5c052900-1e80-11e9-90e1-a12594ca6676.png)

- Blue = IndexService
- Green = BucketServiceName
- Red = BucketService
- Grey = Result/Input

**Comment by vonovak** [comment]
Thanks for reporting. Specifying the platform and adding a repro would be nice. I will not have time to look into this though. Thanks.

**Comment by ulfgebhardt** [comment]
@vonovak 
Done - consider testing it out - its a simple while loop you have to put into your write code

**Comment by suvro24** [comment]
is it fixed in the latest version?

**Comment by sebk** [comment]
I still have the same problem and also with the latest library versions the problem still exists.

I guess it is also the same as https://github.com/oblador/react-native-keychain/issues/208 (?)

**Comment by blankey1337** [comment]
Just ran into this on Android 7.

**Comment by quicksilverr** [comment]
Hey Guys, 

I just across the same issue, even in the version 7.0.0. 
I'm using RSA as the crypto option for android, without which a biometric prompt isn't displayed. But I'm getting string size error.  Thanks @ulfgebhardt for the solution to such a complex problem. 

I was wondering, can we compress our string token and then pass it as a token to `setGenericPassword` and then decompress that token when it is returned from `getGenericPassword`? Is that possible and advisable?
